import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import axios from 'axios'
import { useEffect, useState } from 'react'
const inter = Inter({ subsets: ['latin'] })
import UPLOADFORM from '@/pages/components/uploadForm.js'
export default function Home() {

  const [data, setData] = useState(null)

  const fidel = "hOLA PUTOS"

  const crearDoc = async () => {
    const respuesta = await axios.post('/api/stripers/poststripers')
    console.log(respuesta);
  }

  const leerDocs = async () => {
    const respuesta = await axios.get('/api/stripers/getstripers')
    setData(respuesta.data.ciudades)
  }

  useEffect(() => {
    leerDocs()
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl font-bold underline">
          Hello world!
        </h1>
        <button className='bg-blue-700 text-white' onClick={crearDoc}>SUBIR</button>
        {/* <div className='h-full my-0 border-2'>
          <UPLOADFORM />
        </div> */}
        <div className='m-3 font-sans '>
          <h3 className='text-2xl font-bold'>STRIPERS</h3>
          {data && Object.keys(data).map((key) => (
            <div key={key} className='border-slate-300 border-2 p-1 my-2'>
              <p>Nombre: {data[key].name}</p>
              <p>Estado: {data[key].state}</p>
              <p>País: {data[key].country}</p>
              <p>ID: {data[key].id}</p>
              <p>Descripción: {data[key].desc}</p>
            </div>
          ))}
        </div>
      </main>
    </>
  )
    
}

